
import { Subject, Language } from './types';

export const AVATARS = ['🦁', '🦄', '🚀', '🐱', '🐶', '🦖', '🌟', '🤖', '🦊', '🐼', '🐸', '🐯'];

export const SUBJECTS: Subject[] = [
  {
    id: 'math',
    nameAr: 'الرياضيات',
    nameEn: 'Math',
    nameFr: 'Mathématiques',
    icon: '🧮',
    color: 'bg-blue-100 text-blue-600 border-blue-200 hover:bg-blue-200 dark:bg-blue-900/40 dark:text-blue-200 dark:border-blue-800 dark:hover:bg-blue-900/60',
    descriptionAr: 'تعلم الأرقام والحساب بذكاء',
    descriptionEn: 'Learn numbers and logic',
    descriptionFr: 'Apprendre les nombres et la logique'
  },
  {
    id: 'science',
    nameAr: 'العلوم',
    nameEn: 'Science',
    nameFr: 'Sciences',
    icon: '🔬',
    color: 'bg-green-100 text-green-600 border-green-200 hover:bg-green-200 dark:bg-green-900/40 dark:text-green-200 dark:border-green-800 dark:hover:bg-green-900/60',
    descriptionAr: 'اكتشف أسرار الكون والطبيعة',
    descriptionEn: 'Discover nature and space',
    descriptionFr: 'Découvrir la nature et l\'espace'
  },
  {
    id: 'history',
    nameAr: 'التاريخ',
    nameEn: 'History',
    nameFr: 'Histoire',
    icon: '📜',
    color: 'bg-amber-100 text-amber-600 border-amber-200 hover:bg-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:border-amber-800 dark:hover:bg-amber-900/60',
    descriptionAr: 'رحلة عبر الزمن والقصص',
    descriptionEn: 'Travel through time',
    descriptionFr: 'Voyager à travers le temps'
  },
  {
    id: 'languages',
    nameAr: 'اللغات',
    nameEn: 'Languages',
    nameFr: 'Langues',
    icon: '🗣️',
    color: 'bg-rose-100 text-rose-600 border-rose-200 hover:bg-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800 dark:hover:bg-rose-900/60',
    descriptionAr: 'تعلم كلمات وجمل جديدة',
    descriptionEn: 'Learn new words',
    descriptionFr: 'Apprendre de nouveaux mots'
  },
  {
    id: 'general',
    nameAr: 'دردشة عامة',
    nameEn: 'Just Chat',
    nameFr: 'Discussion',
    icon: '🤖',
    color: 'bg-violet-100 text-violet-600 border-violet-200 hover:bg-violet-200 dark:bg-violet-900/40 dark:text-violet-200 dark:border-violet-800 dark:hover:bg-violet-900/60',
    descriptionAr: 'اسألني أي شيء!',
    descriptionEn: 'Ask me anything!',
    descriptionFr: 'Demande-moi n\'importe quoi !'
  }
];

export const UI_TEXT = {
  [Language.ARABIC]: {
    welcome: 'مرحباً بك في المعلم الذكي!',
    selectProfile: 'من يستخدم التطبيق؟',
    kidRole: 'أنا طفل',
    parentRole: 'ولي أمر',
    greeting: 'أهلاً يا بطل!',
    chooseSubject: 'ماذا تريد أن تتعلم اليوم؟',
    typeMessage: 'اكتب رسالتك هنا...',
    send: 'إرسال',
    back: 'رجوع',
    settings: 'الإعدادات',
    dashboard: 'لوحة التحكم',
    progress: 'تقدم التعلم',
    switchLang: 'English',
    micStart: 'تحدث',
    micStop: 'توقف',
    tutorName: 'المعلم الذكي',
    ageGroup: 'الفئة العمرية: 8-14',
    parentArea: 'منطقة الآباء',
    parentPin: 'أدخل رمز الحماية',
    unlock: 'فتح القفل',
    errorGeneric: 'عذراً، حدث خطأ ما. حاول مرة أخرى.',
    thinking: 'جاري التفكير...',
    whoIsLearning: 'من سيتعلم اليوم؟',
    addChild: 'إضافة ملف طفل جديد',
    grade: 'الصف الدراسي',
    pace: 'سرعة التعلم',
    voice: 'الصوت المفضل',
    speakingRate: 'سرعة الكلام',
    male: 'ذكر',
    female: 'أنثى',
    slow: 'تمهل (بسيط)',
    normal: 'عادي',
    fast: 'سريع (متقدم)',
    save: 'حفظ',
    cancel: 'إلغاء',
    name: 'الاسم',
    age: 'العمر',
    avatar: 'الصورة الرمزية',
    selectAvatar: 'اختر صورة رمزية',
    createProfile: 'إنشاء ملف شخصي',
    fillAll: 'يرجى ملء جميع الحقول',
    smartLesson: 'درس ذكي (مسح ضوئي)',
    uploadPage: 'رفع صفحة / صورة',
    library: 'مكتبتي',
    bookTitle: 'اسم الكتاب (اختياري)',
    pageNumber: 'رقم الصفحة',
    analyze: 'شرح الدرس',
    analyzing: 'جاري تحليل الدرس...',
    lessonSaved: 'تم حفظ الدرس في المكتبة!',
    viewLesson: 'عرض الدرس',
    noLessons: 'لا توجد دروس محفوظة بعد.',
    delete: 'حذف',
    uploadTip: 'التقط صورة واضحة لصفحة الكتاب أو الواجب.',
    offline: 'وضع عدم الاتصال',
    offlineWarning: 'لا يوجد اتصال بالإنترنت. يمكنك تصفح مكتبتك فقط.',
    offlineError: 'تحتاج إلى الإنترنت لاستخدام الذكاء الاصطناعي.',
    studyTime: 'وقت التعلم المفضل',
    morning: 'الصباح ☀️',
    afternoon: 'بعد الظهر 🌤️',
    evening: 'المساء 🌙',
    anytime: 'أي وقت ⏰',
    reminderTitle: 'تذكير ذكي',
    reminderMsg1: 'مرحباً! لقد اشتقنا لك. هل أنت مستعد لمغامرة قصيرة؟ 🚀',
    reminderMsg2: 'عقلك العبقري يحتاج إلى تمرين بسيط! 🧠',
    reminderMsg3: 'هل تعلم شيئاً جديداً اليوم؟ لنكتشف معاً! 🌟',
    dismiss: 'لاحقاً',
    letsGo: 'لننطلق!',
    timerStart: 'بدء المؤقت',
    timerStop: 'إيقاف',
    sessionComplete: 'انتهت الجلسة!',
    breakTime: 'أحسنت يا بطل! حان وقت الاستراحة 🧘‍♂️',
    minutes: 'دقيقة',
    resumeStudy: 'متابعة الدراسة',
    nightMode: 'الوضع الليلي',
    parentalLock: 'قفل الأبوين',
    enterPinDesc: 'يرجى إدخل الرمز السري للوصول إلى هذه المنطقة.',
    incorrectPin: 'الرمز غير صحيح، حاول مرة أخرى.',
    forgotPin: 'نسيت الرمز؟ (الافتراضي: 1234)',
    restrictedArea: 'منطقة محمية',
    premiumContent: 'محتوى متميز',
    unlockPremium: 'فتح المحتوى المتميز',
    premiumDesc: 'احصل على دروس متقدمة وتقارير تفصيلية.',
    purchaseSuccess: 'تمت العملية بنجاح! (محاكاة)',
    premiumDashboard: 'لوحة التحكم المميزة',
    premiumGames: 'ألعاب الذكاء',
    premiumMath: 'رياضيات متقدمة',
    premiumScience: 'مختبر العلوم',
    premiumLang: 'تحدي اللغات',
    premiumGuess: 'من أنا؟',
    selectLangTitle: 'اختر اللغة',
    french: 'الفرنسية 🇫🇷',
    english: 'الإنجليزية 🇬🇧',
    spanish: 'الإسبانية 🇪🇸',
    startChallenge: 'بدء التحدي',
    comingSoon: 'قريباً',
    relatedResources: 'مصادر تعليمية مقترحة',
    finishReview: 'إنهاء المراجعة ✅',
    lessonCompleted: 'درس مكتمل! 🌟',
    greatJobLesson: 'أحسنت! لقد أنهيت مراجعة هذا الدرس بنجاح.',
    backToLibrary: 'العودة للمكتبة',
    takeQuiz: 'اختبار سريع 📝',
    quizTitle: 'اختبار الدرس',
    inProgress: 'قيد الدراسة ⏳',
    completed: 'مكتمل ✅',
    resume: 'متابعة',
    yesUnderstood: 'نعم، فهمت! 👍',
    noNotUnderstood: 'لا، لم أفهم 😕',
    movingOn: 'رائع! لننتقل للخطوة التالية.',
    explainingBetter: 'لا بأس، سأشرحها لك بطريقة أسهل بكثير.',
  },
  [Language.ENGLISH]: {
    welcome: 'Welcome to SmartKids Tutor!',
    selectProfile: 'Who is using the app?',
    kidRole: 'I am a Kid',
    parentRole: 'Parent',
    greeting: 'Hello Hero!',
    chooseSubject: 'What do you want to learn?',
    typeMessage: 'Type here...',
    send: 'Send',
    back: 'Back',
    settings: 'Settings',
    dashboard: 'Dashboard',
    progress: 'Learning Progress',
    switchLang: 'Français',
    micStart: 'Speak',
    micStop: 'Stop',
    tutorName: 'Smart Tutor',
    ageGroup: 'Ages: 8-14',
    parentArea: 'Parents Area',
    parentPin: 'Enter Security PIN',
    unlock: 'Unlock',
    errorGeneric: 'Oops, something went wrong. Try again.',
    thinking: 'Thinking...',
    whoIsLearning: 'Who is learning today?',
    addChild: 'Add New Child Profile',
    grade: 'Grade Level',
    pace: 'Learning Pace',
    voice: 'Preferred Voice',
    speakingRate: 'Speaking Rate',
    male: 'Male',
    female: 'Female',
    slow: 'Slow & Simple',
    normal: 'Normal',
    fast: 'Fast & Advanced',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    age: 'Age',
    avatar: 'Avatar',
    selectAvatar: 'Select an Avatar',
    createProfile: 'Create Profile',
    fillAll: 'Please fill all fields',
    smartLesson: 'Smart Lesson (Scan)',
    uploadPage: 'Upload Page / Image',
    library: 'My Library',
    bookTitle: 'Book Title (Optional)',
    pageNumber: 'Page Number',
    analyze: 'Explain Lesson',
    analyzing: 'Analyzing lesson...',
    lessonSaved: 'Lesson saved to Library!',
    viewLesson: 'View Lesson',
    noLessons: 'No saved lessons yet.',
    delete: 'Delete',
    uploadTip: 'Take a clear photo of your book page or homework.',
    offline: 'Offline Mode',
    offlineWarning: 'No internet connection. You can only access your Library.',
    offlineError: 'You need internet to use AI features.',
    studyTime: 'Preferred Study Time',
    morning: 'Morning ☀️',
    afternoon: 'Afternoon 🌤️',
    evening: 'Evening 🌙',
    anytime: 'Anytime ⏰',
    reminderTitle: 'Smart Reminder',
    reminderMsg1: 'Hi! We missed you. Ready for a quick adventure? 🚀',
    reminderMsg2: 'Your genius brain needs a little workout! 🧠',
    reminderMsg3: 'Did you learn something new today? Let\'s explore! 🌟',
    dismiss: 'Not Now',
    letsGo: 'Let\'s Go!',
    timerStart: 'Start Timer',
    timerStop: 'Stop',
    sessionComplete: 'Session Complete!',
    breakTime: 'Great job Hero! Time for a break 🧘‍♂️',
    minutes: 'min',
    resumeStudy: 'Resume Study',
    nightMode: 'Night Mode',
    parentalLock: 'Parental Lock',
    enterPinDesc: 'Please enter the PIN to access this area.',
    incorrectPin: 'Incorrect PIN, try again.',
    forgotPin: 'Forgot PIN? (Default: 1234)',
    restrictedArea: 'Restricted Area',
    premiumContent: 'Premium Content',
    unlockPremium: 'Unlock Premium',
    premiumDesc: 'Get advanced lessons and detailed reports.',
    purchaseSuccess: 'Purchase Successful! (Simulated)',
    premiumDashboard: 'Premium Dashboard',
    premiumGames: 'Brain Games',
    premiumMath: 'Advanced Math',
    premiumScience: 'Science Lab',
    premiumLang: 'Language Challenge',
    premiumGuess: 'Guess Who?',
    selectLangTitle: 'Select Language',
    french: 'French 🇫🇷',
    english: 'English 🇬🇧',
    spanish: 'Spanish 🇪🇸',
    startChallenge: 'Start Challenge',
    comingSoon: 'Coming Soon',
    relatedResources: 'Related Resources',
    finishReview: 'Finish Review ✅',
    lessonCompleted: 'Lesson Completed! 🌟',
    greatJobLesson: 'Great job! You successfully reviewed this lesson.',
    backToLibrary: 'Back to Library',
    takeQuiz: 'Take Quiz 📝',
    quizTitle: 'Lesson Quiz',
    inProgress: 'In Progress ⏳',
    completed: 'Completed ✅',
    resume: 'Resume',
    yesUnderstood: 'YES, understood! 👍',
    noNotUnderstood: 'NO, not really 😕',
    movingOn: 'Great! Let\'s move to the next part.',
    explainingBetter: 'No problem! I will explain it again in a much simpler way.',
  },
  [Language.FRENCH]: {
    welcome: 'Bienvenue chez SmartKids Tutor !',
    selectProfile: 'Qui utilise l\'application ?',
    kidRole: 'Je suis un enfant',
    parentRole: 'Parent',
    greeting: 'Bonjour Héros !',
    chooseSubject: 'Que veux-tu apprendre ?',
    typeMessage: 'Écris ici...',
    send: 'Envoyer',
    back: 'Retour',
    settings: 'Paramètres',
    dashboard: 'Tableau de bord',
    progress: 'Progrès d\'apprentissage',
    switchLang: 'عربي',
    micStart: 'Parler',
    micStop: 'Arrêter',
    tutorName: 'Tuteur Intelligent',
    ageGroup: 'Âges : 8-14',
    parentArea: 'Zone Parents',
    parentPin: 'Entrez le PIN',
    unlock: 'Déverrouiller',
    errorGeneric: 'Oups, un problème est survenu.',
    thinking: 'Réflexion...',
    whoIsLearning: 'Qui apprend aujourd\'hui ?',
    addChild: 'Ajouter un profil enfant',
    grade: 'Niveau scolaire',
    pace: 'Rythme',
    voice: 'Voix préférée',
    speakingRate: 'Vitesse de parole',
    male: 'Masculin',
    female: 'Féminin',
    slow: 'Lent et Simple',
    normal: 'Normal',
    fast: 'Rapide',
    save: 'Enregistrer',
    cancel: 'Annuler',
    name: 'Nom',
    age: 'Âge',
    avatar: 'Avatar',
    selectAvatar: 'Choisir un avatar',
    createProfile: 'Créer le profil',
    fillAll: 'Veuillez remplir tous les champs',
    smartLesson: 'Leçon intelligente',
    uploadPage: 'Charger une page',
    library: 'Ma bibliothèque',
    bookTitle: 'Titre du livre',
    pageNumber: 'Page',
    analyze: 'Expliquer la leçon',
    analyzing: 'Analyse en cours...',
    lessonSaved: 'Leçon enregistrée !',
    viewLesson: 'Voir la leçon',
    noLessons: 'Aucune leçon pour le moment.',
    delete: 'Supprimer',
    uploadTip: 'Prends une photo claire.',
    offline: 'Mode hors ligne',
    offlineWarning: 'Pas de connexion.',
    offlineError: 'Internet requis pour l\'IA.',
    studyTime: 'Moment d\'étude',
    morning: 'Matin ☀️',
    afternoon: 'Après-midi 🌤️',
    evening: 'Soir 🌙',
    anytime: 'Tout temps ⏰',
    reminderTitle: 'Rappel intelligent',
    reminderMsg1: 'Salut ! Prêt pour une aventure ? 🚀',
    reminderMsg2: 'Ton génie a besoin d\'exercice ! 🧠',
    reminderMsg3: 'Apprenons quelque chose de nouveau ! 🌟',
    dismiss: 'Pas maintenant',
    letsGo: 'C\'est parti !',
    timerStart: 'Démarrer',
    timerStop: 'Arrêter',
    sessionComplete: 'Session finie !',
    breakTime: 'Bien joué ! C\'est l\'heure de la pause 🧘‍♂️',
    minutes: 'min',
    resumeStudy: 'Reprendre',
    nightMode: 'Mode nuit',
    parentalLock: 'Contrôle parental',
    enterPinDesc: 'Entrez le code PIN.',
    incorrectPin: 'Code incorrect.',
    forgotPin: 'Code oublié ? (Défaut : 1234)',
    restrictedArea: 'Zone protégée',
    premiumContent: 'Contenu Premium',
    unlockPremium: 'Débloquer Premium',
    premiumDesc: 'Leçons avancées et rapports.',
    purchaseSuccess: 'Achat réussi !',
    premiumDashboard: 'Tableau Premium',
    premiumGames: 'Jeux cérébraux',
    premiumMath: 'Maths avancées',
    premiumScience: 'Labo Sciences',
    premiumLang: 'Défi Langues',
    premiumGuess: 'Qui suis-je ?',
    selectLangTitle: 'Choisir la langue',
    french: 'Français 🇫🇷',
    english: 'Anglais 🇬🇧',
    spanish: 'Espagnol 🇪🇸',
    startChallenge: 'Démarrer',
    comingSoon: 'Bientôt',
    relatedResources: 'Ressources liées',
    finishReview: 'Finir la révision ✅',
    lessonCompleted: 'Leçon terminée ! 🌟',
    greatJobLesson: 'Bravo ! Révision réussie.',
    backToLibrary: 'Retour bibliothèque',
    takeQuiz: 'Petit Quiz 📝',
    quizTitle: 'Quiz de la leçon',
    inProgress: 'En cours ⏳',
    completed: 'Terminé ✅',
    resume: 'Continuer',
    yesUnderstood: 'OUI, compris ! 👍',
    noNotUnderstood: 'NON, pas vraiment 😕',
    movingOn: 'Super ! Passons à la suite.',
    explainingBetter: 'Pas de souci ! Je réexplique simplement.',
  }
};